# Generated by Django 4.2.1 on 2023-05-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
