# Generated by Django 4.2.1 on 2023-05-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
